src/back-end/Senparc.Areas.Admin/Areas/Admin/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Senparc.Areas.Admin.Domain;
using Senparc.CO2NET.Extensions;
using Senparc.CO2NET.Trace;
using Senparc.Areas.Admin.Domain.Models.VD;
using Senparc.Ncf.AreaBase.Admin.Filters;
using Senparc.Ncf.Core.Models;
using Senparc.Ncf.Service;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Senparc.Areas.Admin.Domain.Models;
using System;
using Senparc.Ncf.Core.Exceptions;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    [AllowAnonymous]
    [IgnoreAntiforgeryToken]
    [BindProperties()]
    public class LoginModel : BasePageModel/* BaseAdminPageModel*/
    {
        //[BindProperty]
        //[FromBody]
        //[Required(ErrorMessage = "请输入用户名")]
        //public string Name { get; set; }

        //[BindProperty]
        //[FromBody]
        //[Required(ErrorMessage = "请输入密码")]
        //public string Password { get; set; }

        //绑定参数
        //[BindProperty(SupportsGet = true)]
        //public string ReturnUrl { get; set; }



        private readonly AdminUserInfoService _userInfoService;
        public LoginModel(AdminUserInfoService userInfoService)
        {
            this._userInfoService = userInfoService;
        }


        public async Task<IActionResult> OnGetAsync(string ReturnUrl)
        {
            await Task.CompletedTask;
            //是否已经登录
            //var logined = await base.CheckLoginedAsync(AdminAuthorizeAttribute.AuthenticationScheme);//判断登录

            //if (logined)
            //{
            //    if (ReturnUrl.IsNullOrEmpty())
            //    {
            //        return RedirectToPage("/Index");
            //    }
            //    return LocalRedirect(ReturnUrl.UrlDecode());
            //}

            return null;
        }

        //public async Task<IActionResult> OnPostAsync(/*[Required]string name,string password*/)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return null;
        //    }
        //    string errorMsg = null;

        //    var userInfo = await _userInfoService.GetUserInfo(this.Name);
        //    if (userInfo == null)
        //    {
        //        //errorMsg = "账号或密码错误！错误代码：101。";
        //        ModelState.AddModelError(nameof(this.Password), "账号或密码错误！错误代码：101。");
        //    }
        //    else if (_userInfoService.TryLogin(this.Name, this.Password, true) == null)
        //    {
        //        //errorMsg = "账号或密码错误！错误代码：102。";
        //        ModelState.AddModelError(nameof(this.Password), "账号或密码错误！错误代码：102。");
        //    }

        //    if (!errorMsg.IsNullOrEmpty() || !ModelState.IsValid)
        //    {
        //        //this.MessagerList = new List<Messager>
        //        //{
        //        //    new Messager(Senparc.Ncf.Core.Enums.MessageType.danger, errorMsg)
        //        //};
        //        return null;
        //    }

        //    if (this.ReturnUrl.IsNullOrEmpty())
        //    {
        //        return RedirectToPage("/Index");
        //    }
        //    return LocalRedirect(this.ReturnUrl.UrlDecode());
        //}

        public async Task<IActionResult> OnPostLoginAsync([FromBody] LoginInDto loginInDto/*[Required]string name,string password*/)
        {
            if (!ModelState.IsValid)
            {
                return Ok(new { loginInDto.Name, loginInDto.Password });
            }

            AdminUserInfo userInfo = null;
            try
            {
                userInfo = await _userInfoService.GetUserInfoAsync(loginInDto.Name);
            }
            catch (Exception ex)
            {
                return Ok("pwd", false, ex.Message);
            }

            if (userInfo == null)
            {
                SenparcTrace.SendCustomLog("登录失败", $"用户名：{loginInDto.Name}, 错误：账号或密码错误！101");
                return Ok("pwd", false, "账号或密码错误！");
                //ModelState.AddModelError(nameof(this.Password), "账号或密码错误！");
            }

            try
            {
                //TODO 需要把 userInfo 获取过程封装到下面的方法中，统一处理账号锁定
                if (await _userInfoService.TryLoginAsync(userInfo, loginInDto.Password, true) == null)
                {
                    //ModelState.AddModelError(nameof(this.Password), "账号或密码错误！");
                    SenparcTrace.SendCustomLog("登录失败", $"用户名：{loginInDto.Name}, 错误：账号或密码错误！102");
                    return Ok("pwd", false, "账号或密码错误！");
                }   
                return Ok(true);
            }
            catch (LoginLockException ex)
            {
                SenparcTrace.SendCustomLog("登录失败", $"用户名：{loginInDto.Name}, 错误：{ex.Message}");
                return Ok("pwd", false, ex.Message);
            }
            catch (Exception ex)
            {
                SenparcTrace.SendCustomLog("登录失败", $"用户名：{loginInDto.Name}, 错误：{ex.Message}");
                //其他异常，不返回错误信息
                return Ok("pwd", false, "账号或密码错误！");
            }
        }

        public async Task<IActionResult> OnGetLogoutAsync(string ReturnUrl)
        {
            SenparcTrace.SendCustomLog("管理员退出登录", $"用户名：{base.UserName}");
            await _userInfoService.LogoutAsync();
            if (string.IsNullOrEmpty(ReturnUrl))
            {
                return RedirectToPage(new { area = "Admin" });
            }
            else
            {
                return LocalRedirect(ReturnUrl.UrlDecode());
            }
        }
    }

    public class LoginInDto
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

src/back-end/Senparc.Areas.Admin/Areas/Admin/Pages/Shared/_HeaderPartial.cshtml
@model Senparc.Ncf.AreaBase.Admin.IAdminPageModelBase
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a href="javascript:;" id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a data-toggle="tooltip" data-placement="left" title="退出登录" asp-page="/Login" asp-page-handler="Logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

src/back-end/Senparc.Areas.Admin/Areas/Admin/Pages/Shared/_Layout_Vue.cshtml
@model Senparc.Ncf.AreaBase.Admin.IAdminPageModelBase
@{
    var thisYear = DateTime.Now.Year;
}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="description" content="@ViewData["Title"]" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">
    <!-- 引入样式 -->
    <link href="~/lib/element-ui_2.13.2/element.css" rel="stylesheet" />
    <link href="~/css/Admin/Shared/layout.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    @RenderSection("HeaderContent", false)
    @RenderSection("Style", false)
</head>
<body>
    <div id="app" v-cloak>
        <div class="app-wrapper">
            <el-container>
                @*菜单栏*@
                <el-aside :style="{'width':Store.state.navMenu.isCollapse?'64px':''}" class="el-aside-index">
                    <div :class="[Store.state.navMenu.isCollapse?'head-log2':'head-log']">
                        <a href="/Admin/Index">
                            <img src="~/images/Admin/base/head/logo_230x55.png" alt="Alternate Text" />
                        </a>
                    </div>
                    <el-scrollbar wrap-class="scrollbar-wrapper" style="height:calc(100vh - 80px);">
                        <el-menu :default-active="Store.state.navMenu.activeMenu"
                                 :collapse="Store.state.navMenu.isCollapse"
                                 :background-color="Store.state.navMenu.variables.menuBg"
                                 :text-color="Store.state.navMenu.variables.menuText"
                                 :active-text-color="Store.state.navMenu.variables.menuActiveText"
                                 :unique-opened="false"
                                 :collapse-transition="false"
                                 @@select="menuSelect"
                                 mode="vertical">
                            <sidebar-item v-for="(items,index) in Store.state.navMenu.navMenuList" :key="index" :item="items"></sidebar-item>
                        </el-menu>
                    </el-scrollbar>
                </el-aside>
                <el-container>
                    <el-header>
                        <div class="header-menu">
                            @*切换菜单栏*@
                            <i class="fa fa-indent" aria-hidden="true" @@click="toggleSideBar"></i>
                        </div>
                        @*面包屑*@
                        <div class="header-breadcrumb">
                            <el-breadcrumb separator="/">
                                <el-breadcrumb-item><a href="/Admin/Index">首页</a></el-breadcrumb-item>
                                @RenderSection("breadcrumbs", false)
                            </el-breadcrumb>
                        </div>
                        @*退出*@
                        <div class="header-logout">
                            <el-tooltip class="item" effect="dark" content="退出登录" placement="left">
                                <el-popconfirm confirmButtonText='退出'
                                               cancelButtonText='不用了'
                                               icon="el-icon-info"
                                               iconColor="red"
                                               title="确定退出吗？"
                                               @@on-Confirm="loginout">
                                    <i slot="reference" style="cursor:pointer;" class="fa fa-sign-out" aria-hidden="true"></i>
                                </el-popconfirm>
                            </el-tooltip>
                        </div>
                    </el-header>
                    <el-main>
                        <div class="ifram-wrapper">
                            @*<iframe :src="pageSrc"></iframe>*@
                            @RenderBody()
                        </div>
                    </el-main>
                    <el-footer class="footer">
                        Powered by <a href="https://www.ncf.pub" target="_blank">NeuCharFramework</a> © 2010-@thisYear <a href="https://www.senparc.com" target="_blank">盛派网络</a>
                    </el-footer>
                </el-container>
            </el-container>
        </div>
    </div>
    <!--lib-->
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/element-ui_2.13.2/element.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>
    <script src="~/lib/vuex.js"></script>
    <!--js-->
    <script src="~/js/Admin/store.js"></script>
    <script src="~/js/Admin/axios.js"></script>
    <script src="~/js/Admin/global.js"></script>
    <!--菜单栏-->
    <script src="~/js/Admin/navMenu.js"></script>
    <script src="~/js/Admin/vuePermission.js"></script>
    <script src="~/js/Admin/Pages/Components/Components.js"></script>
    <!--页面js-->
    @*<script src="~/js/Admin/Pages/Index/Index.js"></script>*@
    @RenderSection("scripts", false)
    @Html.AntiForgeryToken()
</body>
</html>

src/back-end/Senparc.Areas.Admin/Areas/Admin/Pages/Shared/_MenuPartial.cshtml
@model Senparc.Ncf.AreaBase.Admin.IAdminPageModelBase
@using Senparc.Ncf.XncfBase;
@using Senparc.Ncf.Core.Areas;
@using Microsoft.AspNetCore.Http;
@inject Senparc.Ncf.Service.SysMenuService _sysMenuService
@inject IHttpContextAccessor _httpContextAccessor
@addTagHelper *, Senparc.Areas.Admin
@{
    var sysMenuDtos = await _sysMenuService.GetMenuTreeDtoByCacheAsync();

    /// <summary>
    /// 判断当前页面是否为 XNCF 模块入口
    /// </summary>
    /// <param name="currentMenuUrl"></param>
    /// <returns></returns>
    string CurrentXncfPage(string currentMenuUrl)
    {
        if (!Model.Uid.IsNullOrEmpty())
        {
            var pathAndQuery = Microsoft.AspNetCore.Http.Extensions.UriHelper.GetEncodedPathAndQuery(_httpContextAccessor.HttpContext.Request);
            if (pathAndQuery.Contains("/Admin/XncfModule/Start", StringComparison.OrdinalIgnoreCase) &&
                currentMenuUrl.Contains(Model.Uid, StringComparison.OrdinalIgnoreCase))
            {
                return "current-page-xncf";
            }
            return "";
        }

        return "";
    }
    /// <summary>
    /// 判断当前页面是否为 XNCF 子页面
    /// </summary>
    /// <param name="currentMenuUrl"></param>
    /// <returns></returns>
    string CurrentXncfSubPage(string currentMenuUrl)
    {
        var pathAndQuery = Microsoft.AspNetCore.Http.Extensions.UriHelper.GetEncodedPathAndQuery(_httpContextAccessor.HttpContext.Request);
        if (pathAndQuery.Contains(currentMenuUrl, StringComparison.OrdinalIgnoreCase) ||
            (ViewData["TempMenuUrl"] is string tempMenuUrl && currentMenuUrl.Contains(tempMenuUrl, StringComparison.OrdinalIgnoreCase)))
        {
            return "current-page-xncf";
        }
        return "";
    }
}


<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title hidden-small">
            @*<a href="/Home/Index" class="site_title">
                    <img src="~/images/Admin/base/head/logo_230x55.png" class="hidden-small" />
                    <img src="~/images/Admin/base/head/logo_70x55.png" class="hidden-lg" />
                </a>*@
            <a href="/" class="site_title">
                <img src="~/images/Admin/base/head/logo_230x55.png" />
            </a>
        </div>

        <div class="clearfix"></div>
        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="~/images/Admin/base/head/logo_128x128.png" class="img-circle profile_img" style="background-color:transparent" />
            </div>
            <div class="profile_info" style="padding: 25px 0px 10px;">
                <span>Welcome,</span>
                <h2>@Model.UserName</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                @*<h3>菜单</h3>*@
                <ul class="nav side-menu">
                    <li>
                        <a href="~/Admin/Index">首页</a>
                    </li>
                    @foreach (var item in sysMenuDtos)
                    {
                        //判断是否隐藏模块管理单元
                        var hideXncfModuleManager = item.MenuName == "扩展模块" && Model.FullSystemConfig.HideModuleManager == true;

                        @if (!hideXncfModuleManager)
                        {
                            //显示扩展模块，建立一级目录
                            @Html.Raw(@"<li>")

                            <a href="@item.Url">
                                @if (!string.IsNullOrEmpty(item.Icon))
                                {
                                    <i class="@item.Icon"></i>
                                }
                                @item.MenuName

                            </a>
                        }

                        @if (item.Children != null)
                        {
                            @if (!hideXncfModuleManager)
                            {
                                //显示扩展模块，建立二级目录
                                @Html.Raw(@"<ul class=""nav child_menu"">")
                            }
                            @foreach (var childrenItem in item.Children.Where(_ => _.IsMenu))
                            {
                                if (hideXncfModuleManager && childrenItem.MenuName=="模块管理")
                                {
                                    continue;//隐藏“模块管理”菜单
                                }
                                <li>
                                    @{
                                        var xncfRegister = Model.XncfRegisterList.FirstOrDefault(z => !childrenItem.Url.IsNullOrEmpty() && childrenItem.Url.Contains($"uid={z.Uid}", StringComparison.OrdinalIgnoreCase));
                                    }
                                    @if (xncfRegister != null)
                                    {
                                        if (xncfRegister is Senparc.Ncf.Core.Areas.IAreaRegister xncfAreapage &&
                                        xncfAreapage.AreaPageMenuItems.Count() > 0)
                                        {
                                            //这是一个 XNCF UI 模块菜单，并且包含多个菜单配置
                                            <a><i class="@childrenItem.Icon"></i> @childrenItem.MenuName<span class="fa fa-chevron-down"></span></a>
                                            <ul class="nav child_menu">
                                                <li class="sub_menu @(hideXncfModuleManager?"":"xncf_area_submenu")">
                                                    <a href="@childrenItem.Url" class="@CurrentXncfPage(childrenItem.Url)">
                                                        <i class="fa fa-gear"></i>
                                                        <text>设置/执行</text>
                                                    </a>
                                                </li>
                                                @foreach (var xncfSubMenu in xncfAreapage.AreaPageMenuItems)
                                                {
                                                    <li class="@(hideXncfModuleManager?"":"xncf_area_submenu")">
                                                        <a href="@xncfSubMenu.Url" class="@CurrentXncfSubPage(xncfSubMenu.Url)">
                                                            @if (!string.IsNullOrEmpty(xncfSubMenu.Icon))
                                                            {
                                                                <i class="@xncfSubMenu.Icon"></i>
                                                            }
                                                            @xncfSubMenu.Name
                                                        </a>
                                                    </li>
                                                }
                                            </ul>
                                        }
                                        else
                                        {
                                            //这是一个普通的 XNCF（可能只包含 Functions）菜单
                                            <a href="@childrenItem.Url" class="@CurrentXncfPage(childrenItem.Url)">
                                                @if (!string.IsNullOrEmpty(childrenItem.Icon))
                                                {
                                                    <i class="@childrenItem.Icon"></i>
                                                }
                                                @childrenItem.MenuName
                                            </a>
                                        }
                                    }
                                    else
                                    {
                                        //其他菜单，如系统或自定义菜单
                                        <a href="@childrenItem.Url">
                                            @if (!string.IsNullOrEmpty(childrenItem.Icon))
                                            {
                                                <i class="@childrenItem.Icon"></i>
                                            }
                                            @childrenItem.MenuName
                                        </a>
                                    }
                                </li>
                            }
                            @if (!hideXncfModuleManager)
                            {
                                //显示扩展模块，二级目录结束
                                @Html.Raw(@"</ul>")
                            }
                        }
                        @if (!hideXncfModuleManager)
                        {
                            //显示扩展模块，一级目录结束
                            @Html.Raw(@"</li>")
                        }
                    }
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
    </div>
</div>
<!-- /menu footer buttons -->

src/back-end/Senparc.Areas.Admin/Areas/Admin/Pages/Shared/_XncfModuleLayout.cshtml
@* XNCF 模块页面的模板页 *@
@model Senparc.Ncf.AreaBase.Admin.AdminXncfModulePageModelBase
@using Senparc.Ncf.Core.Areas;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor _httpContextAccessor
@{
    Layout = "_Layout";
}
@{
    var subTitle = ViewData["Title"];
    ViewData["Title"] = Model.XncfModuleDto?.MenuName + " - " + subTitle;
}
@section HeaderContent{
    @RenderSection("HeaderContent", false)
}
@section Style{
    @RenderSection("Style", false)
}
@section modal{
    @RenderSection("modal", false)
}
@section explanations{
    @RenderSection("explanations", false)
}
@section breadcrumbs{
    <li>扩展模块</li>
    <li>模块管理</li>
    <li>@Model.XncfModuleDto.MenuName</li>
    @RenderSection("breadcrumbs", false)
    @if (!IsSectionDefined("breadcrumbs"))
    {
        <li>@subTitle</li>
    }
}
@section filter{
    @RenderSection("filter", false)
}
@section scripts{
    @RenderSection("scripts", false)
}

<div class="div">
    @*左侧*@
    <div class="col-md-2 col-sm-2" style="background:#586e83;">
        <div class="x_content">
            <div id="sidebar-sub-menu" class="main_menu_side hidden-print main_menu">
                <div class="menu_section active">
                    <ul class="nav side-menu" style="">
                        <li><a asp-page="../XncfModule/Start" asp-route-uid="@Model.XncfRegister.Uid"><i class="fa fa-chevron-left"></i> 返回</a></li>
                    </ul>
                    @await Html.PartialAsync("_XncfModuleLayout_Menu", Model.XncfRegister)

                    @if (IsSectionDefined("subMenu"))
                    {
                        <ul class="nav side-menu" style="">
                            @RenderSection("subMenu", false)
                        </ul>
                    }
                </div>
            </div>
        </div>
    </div>

    @*右侧*@
    <div class="col-md-10">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="@Model.XncfRegister.Icon"></i> &nbsp;  @subTitle</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @RenderBody()
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>

src/back-end/Senparc.Areas.Admin/Areas/Admin/Pages/Shared/_XncfModuleLayout_Menu.cshtml
@* XNCF 模块页面的模板页的菜单部分 *@
@model IAreaRegister
@using Senparc.Ncf.Core.Areas;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor _httpContextAccessor
@{
    /// <summary>
    /// 判断当前页面是否为 XNCF 子页面
    /// </summary>
    /// <param name="currentMenuUrl"></param>
    /// <returns></returns>
    string CurrentXncfSubPage(string currentMenuUrl)
    {
        var pathAndQuery = Microsoft.AspNetCore.Http.Extensions.UriHelper.GetEncodedPathAndQuery(_httpContextAccessor.HttpContext.Request);
        if (pathAndQuery.Contains(currentMenuUrl, StringComparison.OrdinalIgnoreCase) ||
            (ViewData["TempMenuUrl"] is string tempMenuUrl && currentMenuUrl.Contains(tempMenuUrl, StringComparison.OrdinalIgnoreCase)))
        {
            return "current-sub-page-xncf";
        }
        return "";
    }
}
<ul class="nav side-menu">
    @foreach (var menu in Model.AreaPageMenuItems)
    {
        <li class="xncf_area_submenu @CurrentXncfSubPage(menu.Url)"><a href="@menu.Url"><i class="@menu.Icon"></i> @menu.Name</a></li>
    }
</ul>